---
- name: link dotfiles
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - { src: "~/.dotfiles/config/init.vim", dest: "~/.config/nvim/init.vim" }
    - { src: "~/.dotfiles/config/.tmux.conf", dest: "~/.config/tmux/.tmux.conf" }
    - { src: "~/.dotfiles/config/com.googlecode.iterm2.plist", dest: "~/Library/Preferences/com.googlecode.iterm2.plist" }
    - { src: "~/.dotfiles/config/.aliases", dest: "~/.config/zsh/.aliases" }
    - { src: "~/.dotfiles/config/.zshrc", dest: "~/.config/zsh/.zshrc" }
    - { src: "~/.dotfiles/config/.zshenv", dest: "~/.config/zsh/.zshenv" }
