---
- name: link dotfiles
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - { src: "~/.dotfiles/config/init.vim", dest: "~/.config/nvim/.init.vim"}
    - { src: "~/.dotfiles/config/init.vim", dest: "~/.config/nvim/.init.vim"}
    - { src: "~/.dotfiles/config/com.googlecode.iterm2.plist", dest: "~/Library/Preferences/com.googlecode.iterm2.plist"}
