---
- name: Include brew taps list
  include_vars: vars/taps.yaml
  tags:
    - brew_taps

- name: Include brew formula list
  include_vars: vars/formula.yaml
  tags:
    - brew_formula

- name: Include brew casks list
  include_vars: vars/casks.yaml
  tags:
    - brew_cask

- name: Include APT package list
  include_vars: vars/apt.yaml
  tags:
    - apt

- block:
  - name: Update/Upgrade Homebrew
    homebrew:
      update_homebrew: true
      upgrade_all: true
    tags:
      - brew_taps
      - brew_formula
      - brew_cask

  - name: Manage taps
    homebrew_tap:
      name: "{{ item.key }}"
      state: "{{ item.value.state | default('present') }}"
    with_dict: "{{taps}}"
    tags:
      - brew_taps

  - name: Manage formula
    homebrew:
      name: "{{ item.key }}"
      install_options: "{{ item.value.options | default(omit) }}"
      state: "{{ item.value.state | default('present') }}"
    with_dict: "{{formula}}"
    tags:
      - brew_formula

  - name: Manage casks
    homebrew_cask:
      name: "{{ item.key }}"
      state: "{{ item.value.state | default('present') }}"
    with_dict: "{{casks}}"
    tags:
      - brew_cask

  when: ansible_os_family == "Darwin"

- block:
  - name: Update/Upgrade apt
    apt:
      update_cache: true
      upgrade: dist

  - name: Manage apt packages
    apt:
      name: "{{ item.key }}"
      state: "{{ item.value.state | default('latest') }}"
    with_dict: "{{apt}}"

  become: true
  when: ansible_os_family == "Debian"
  tags: apt
