---
- name: Playbook to manage my dotfiles
  hosts: localhost
  connection: local
  tasks:
    - name: Make sure dotfiles are present
      git:
        repo: https://github.com/oemilsson/dotfiles
        dest: ~/.dotfiles

    - name: Enable tty_tickets
      lineinfile:
        dest: /etc/sudoers
        state: present
        line: "Defaults tty_tickets"
        validate: "visudo -cf %s"
      become: yes
      when: ansible_os_family == "Darwin"

    - name: Install oh-my-zsh
      git:
        repo: https://github.com/robbyrussell/oh-my-zsh.git
        dest: ~/.local/share/oh-my-zsh
        update: yes

    - name: Install tmux plugin manager
      git:
        repo: https://github.com/tmux-plugins/tpm.git
        dest: ~/.local/share/tpm
        update: yes

    - name: Download k3s binary x64
      get_url:                                                           
        url: https://github.com/rancher/k3s/releases/download/v.0.5.0/k3s
        dest: /usr/local/bin/k3s
        owner: root
        group: root
        mode: 755
      when: ( ansible_facts.architecture == "x86_64" )

    - name: Create folder
      file:
        path: "{{item}}"
        state: directory
      loop:
        - "~/.config/tmux/"
        - "~/.config/nvim/"

    - include: tasks/link_files.yaml
      tags:
        - links

    - include: tasks/packages.yaml
      tags:
        - packages

    - include: tasks/shells.yaml
      tags:
        - shells
